slice_name: ten_mnemonic_chart
viz_type: table
params:
  adhoc_filters: []
  all_columns:
  - service
  color_pn: true
  datasource: 11__table
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: table
query_context: '{"datasource": {"id": 11, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "filters": [], "extras": {"time_grain_sqla": "P1D",
  "time_range_endpoints": ["inclusive", "exclusive"], "having": "", "having_druid":
  [], "where": ""}, "applied_time_extras": {}, "columns": ["service"], "orderby":
  [], "annotation_layers": [], "row_limit": 10000, "timeseries_limit": 0, "order_desc":
  true, "url_params": {}, "custom_params": {}, "custom_form_data": {}, "post_processing":
  []}], "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 885dcd5c-5ac1-4151-849e-c6ee49cd426f
version: 1.0.0
dataset_uuid: 16509982-17c4-4116-bf14-4780c34307d9
